# SPDX-License-Identifier: Apache-2.0
# Copyright 2024 Canonical Ltd.

name: IOSMCN Main workflow

on:
  pull_request:
    branches:
      - iosmcnmaster
  push:
    branches:
      - iosmcnmaster

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ios-mcn-core'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Build
        run: go build ./...

  unit-tests:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ios-mcn-core'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: Unit tests
        run: go test ./...
  
  license-check:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ios-mcn-core'
    steps:
      - uses: actions/checkout@v4

      - name: reuse lint
        uses: fsfe/reuse-action@v3

  fossa-check:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ios-mcn-core'
    steps:
      - uses: actions/checkout@v4

      - name: FOSSA scan
        uses: fossa-contrib/fossa-action@v3
        with:
          fossa-api-key: 0c3bbcdf20e157bbd487dae173751b28
  lint:
    name: lint
    runs-on: ubuntu-latest
    if: github.repository_owner == 'ios-mcn-core'
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v4.0.0
        with:
          version: latest
          args: -v --config ./.golangci.yml
